application: ckid-ckid
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /api.*
  script: Upload.application

- url: /task.*
  script: Task.application

- url: /_ah/spi/.*
  script: api.api

- url: /
  static_files: client/index.html
  upload: client/index.html

- url: /
  static_dir: client

libraries:
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest
- name: webapp2
  version: 2.5.2
